import { Fish, FishRarityId } from '../../types';

export const FISH: Fish[] = [
    // --- TIER 1: SURFACE (1-10) ---
    { id: 1, name: "Digital Guppy", description: "A small, low-poly fish.", probability: 2, color: "text-orange-300", glowColor: "#fdba74", tierName: "Common", rarityId: FishRarityId.COMMON },
    { id: 2, name: "Byte Minnow", description: "8 of these make a snack.", probability: 3, color: "text-blue-300", glowColor: "#93c5fd", tierName: "Common", rarityId: FishRarityId.COMMON },
    { id: 3, name: "Pixel Carp", description: "Scales look like squares.", probability: 4, color: "text-yellow-600", glowColor: "#ca8a04", tierName: "Common", rarityId: FishRarityId.COMMON },
    { id: 4, name: "Static Trout", description: "Makes a buzzing noise.", probability: 5, color: "text-neutral-400", glowColor: "#a3a3a3", tierName: "Common", rarityId: FishRarityId.COMMON },
    { id: 5, name: "Neon Tetra", description: "Glows in the dark web.", probability: 6, color: "text-fuchsia-400", glowColor: "#e879f9", tierName: "Common", rarityId: FishRarityId.COMMON },
    { id: 6, name: "Binary Bass", description: "01000010 01100001 01110011 01110011", probability: 8, color: "text-green-700", glowColor: "#15803d", tierName: "Common", rarityId: FishRarityId.COMMON },
    { id: 7, name: "Glitch Goldfish", description: "Flickers between orange and void.", probability: 10, color: "text-amber-500 animate-pulse", glowColor: "#f59e0b", tierName: "Common", rarityId: FishRarityId.COMMON },
    { id: 8, name: "Data Crab", description: "Moves sideways through the firewall.", probability: 12, color: "text-red-400", glowColor: "#f87171", tierName: "Common", rarityId: FishRarityId.COMMON },
    { id: 9, name: "Rusty Can", description: "Someone threw this in the server pool.", probability: 15, color: "text-stone-500", glowColor: "#78716c", tierName: "Trash", rarityId: FishRarityId.TRASH },
    { id: 10, name: "Old Boot", description: "Boot.exe has stopped working.", probability: 20, color: "text-yellow-900", glowColor: "#451a03", tierName: "Trash", rarityId: FishRarityId.TRASH },
    // --- TIER 2: REEF (11-20) ---
    { id: 11, name: "Cyber Salmon", description: "Swims upstream against the data stream.", probability: 25, color: "text-rose-400", glowColor: "#fb7185", tierName: "Uncommon", rarityId: FishRarityId.UNCOMMON },
    { id: 12, name: "Electric Eel", description: "Powered by USB-C.", probability: 30, color: "text-yellow-400", glowColor: "#facc15", tierName: "Uncommon", rarityId: FishRarityId.UNCOMMON },
    { id: 13, name: "Source Code Squid", description: "Ink is pure black #000000.", probability: 40, color: "text-black bg-white px-1", glowColor: "#ffffff", tierName: "Uncommon", rarityId: FishRarityId.UNCOMMON },
    { id: 14, name: "Firewall Puffer", description: "Expands to block ports.", probability: 50, color: "text-red-600", glowColor: "#dc2626", tierName: "Uncommon", rarityId: FishRarityId.UNCOMMON },
    { id: 15, name: "Search Engine Shark", description: "Smells your browser history.", probability: 60, color: "text-blue-600", glowColor: "#2563eb", tierName: "Predator", rarityId: FishRarityId.PREDATOR },
    { id: 16, name: "Encrypted Ray", description: "Needs a key to see clearly.", probability: 75, color: "text-neutral-300 blur-[1px]", glowColor: "#d4d4d4", tierName: "Rare", rarityId: FishRarityId.RARE },
    { id: 17, name: "GPU Jellyfish", description: "Processes graphics while floating.", probability: 100, color: "text-cyan-400", glowColor: "#22d3ee", tierName: "Rare", rarityId: FishRarityId.RARE },
    { id: 18, name: "Fiber Optic Flounder", description: "Transmits light through its body.", probability: 125, color: "text-white", glowColor: "#ffffff", tierName: "Rare", rarityId: FishRarityId.RARE },
    { id: 19, name: "Packet Loss Pike", description: "Now you see it, now you don't.", probability: 150, color: "text-neutral-500 animate-pulse", glowColor: "#737373", tierName: "Rare", rarityId: FishRarityId.RARE },
    { id: 20, name: "Cookie Cutter Shark", description: "Steals your login cookies.", probability: 200, color: "text-orange-800", glowColor: "#9a3412", tierName: "Rare", rarityId: FishRarityId.RARE },
    // --- TIER 3: DEEP (21-30) ---
    { id: 21, name: "Deep Web Angler", description: "Lures prey with a fake link.", probability: 300, color: "text-purple-400", glowColor: "#c084fc", tierName: "Deep", rarityId: FishRarityId.DEEP },
    { id: 22, name: "VPN Viperfish", description: "Masks its location.", probability: 400, color: "text-green-400", glowColor: "#4ade80", tierName: "Deep", rarityId: FishRarityId.DEEP },
    { id: 23, name: "Blobfish.png", description: "Low resolution compression artifacts.", probability: 500, color: "text-pink-300 blur-sm", glowColor: "#f9a8d4", tierName: "Deep", rarityId: FishRarityId.DEEP },
    { id: 24, name: "Blockchain Barracuda", description: "Verified ownership of bite marks.", probability: 600, color: "text-yellow-600", glowColor: "#ca8a04", tierName: "Crypto", rarityId: FishRarityId.CRYPTO },
    { id: 25, name: "Mining Rig Marlin", description: "Generates heat.", probability: 750, color: "text-red-500", glowColor: "#ef4444", tierName: "Crypto", rarityId: FishRarityId.CRYPTO },
    { id: 26, name: "Phishing Piranha", description: "Sends fake emails.", probability: 1000, color: "text-red-700", glowColor: "#b91c1c", tierName: "Malware", rarityId: FishRarityId.MALWARE },
    { id: 27, name: "Trojan Seahorse", description: "Looks like a gift.", probability: 1250, color: "text-amber-700", glowColor: "#b45309", tierName: "Malware", rarityId: FishRarityId.MALWARE },
    { id: 28, name: "Worm Eel", description: "Self-replicating.", probability: 1500, color: "text-lime-600", glowColor: "#65a30d", tierName: "Malware", rarityId: FishRarityId.MALWARE },
    { id: 29, name: "Spyware Starfish", description: "Sticks to you and watches.", probability: 2000, color: "text-indigo-500", glowColor: "#6366f1", tierName: "Malware", rarityId: FishRarityId.MALWARE },
    { id: 30, name: "Ransomware Ray", description: "Encrypts your other fish.", probability: 2500, color: "text-red-900", glowColor: "#7f1d1d", tierName: "Malware", rarityId: FishRarityId.MALWARE },
    // --- TIER 4: ABYSS (31-40) ---
    { id: 31, name: "Void Leviathan", description: "Massive entity of null data.", probability: 5000, color: "text-violet-950 drop-shadow-[0_0_10px_#4c1d95]", glowColor: "#4c1d95", tierName: "Abyssal", rarityId: FishRarityId.ABYSSAL },
    { id: 32, name: "Null Pointer Nautilus", description: "Points to nothing.", probability: 7500, color: "text-neutral-600", glowColor: "#525252", tierName: "Abyssal", rarityId: FishRarityId.ABYSSAL },
    { id: 33, name: "404 Fish", description: "Species not found.", probability: 10000, color: "text-neutral-100", glowColor: "#f5f5f5", tierName: "Error", rarityId: FishRarityId.ERROR },
    { id: 34, name: "Infinite Loop Loach", description: "Swims in circles forever.", probability: 15000, color: "text-teal-400", glowColor: "#2dd4bf", tierName: "Error", rarityId: FishRarityId.ERROR },
    { id: 35, name: "Kernel Panic Kraken", description: "Crashes the OS on surfacing.", probability: 25000, color: "text-red-600 animate-pulse", glowColor: "#dc2626", tierName: "System", rarityId: FishRarityId.SYSTEM },
    { id: 36, name: "Root Access Ray", description: "Grants full control.", probability: 40000, color: "text-green-500", glowColor: "#22c55e", tierName: "System", rarityId: FishRarityId.SYSTEM },
    { id: 37, name: "Ghost in the Shellfish", description: "Possessed by AI.", probability: 60000, color: "text-cyan-200", glowColor: "#a5f3fc", tierName: "AI", rarityId: FishRarityId.AI },
    { id: 38, name: "Neural Net Narwhal", description: "Tusk is an antenna.", probability: 80000, color: "text-purple-500", glowColor: "#a855f7", tierName: "AI", rarityId: FishRarityId.AI },
    { id: 39, name: "Algorithm Algae", description: "Curates your feed.", probability: 100000, color: "text-emerald-600", glowColor: "#059669", tierName: "AI", rarityId: FishRarityId.AI },
    { id: 40, name: "Singularity Shark", description: "Event horizon in its mouth.", probability: 150000, color: "text-black bg-white px-1 animate-pulse", glowColor: "#000000", tierName: "Cosmic", rarityId: FishRarityId.COSMIC },
    // --- TIER 5: LEGENDARY (41-50) ---
    { id: 41, name: "The Glitch Ness Monster", description: "A myth made of bugs.", probability: 250000, color: "text-fuchsia-500 animate-bounce", glowColor: "#d946ef", tierName: "Cryptid", rarityId: FishRarityId.CRYPTID },
    { id: 42, name: "Cthulhu.exe", description: "Do not run this file.", probability: 500000, color: "text-green-900 drop-shadow-[0_0_15px_#14532d]", glowColor: "#14532d", tierName: "Eldritch", rarityId: FishRarityId.ELDRITCH },
    { id: 43, name: "Moby Dick (PDF)", description: "The entire book in one fish.", probability: 750000, color: "text-white", glowColor: "#ffffff", tierName: "Literature", rarityId: FishRarityId.LITERATURE },
    { id: 44, name: "Golden Magikarp", description: "Useless but shiny.", probability: 1000000, color: "text-yellow-400 drop-shadow-[0_0_10px_#facc15]", glowColor: "#facc15", tierName: "Pokemon", rarityId: FishRarityId.POKEMON },
    { id: 45, name: "Time Stream Trout", description: "Caught yesterday.", probability: 2000000, color: "text-blue-400", glowColor: "#60a5fa", tierName: "Temporal", rarityId: FishRarityId.TEMPORAL },
    { id: 46, name: "Schrödinger's Catfish", description: "Alive and dead until caught.", probability: 5000000, color: "text-neutral-400", glowColor: "#a3a3a3", tierName: "Quantum", rarityId: FishRarityId.QUANTUM },
    { id: 47, name: "The Cloud Whale", description: "Stores everyone's photos.", probability: 10000000, color: "text-sky-200 cloud-texture", glowColor: "#bae6fd", tierName: "Server", rarityId: FishRarityId.SERVER },
    { id: 48, name: "Mainframe Megalodon", description: "Apex predator of the net.", probability: 25000000, color: "text-red-950 animate-pulse", glowColor: "#450a0a", tierName: "Boss", rarityId: FishRarityId.BOSS },
    { id: 49, name: "Zero Day Exploit", description: "No patch available.", probability: 50000000, color: "text-red-500 font-mono", glowColor: "#ef4444", tierName: "Critical", rarityId: FishRarityId.CRITICAL },
    { id: 50, name: "Developers Rubber Duck", description: "It solves all bugs.", probability: 100000000, color: "text-yellow-300 animate-spin", glowColor: "#fde047", tierName: "Dev", rarityId: FishRarityId.DEV },
    // --- TIER 6: SKY (51-60) ---
    { id: 51, name: "Cloud Carp", description: "Swims in the cumulus.", probability: 150000000, color: "text-slate-200", glowColor: "#e2e8f0", tierName: "Sky", rarityId: FishRarityId.SKY },
    { id: 52, name: "Rain Ray", description: "Drips constantly.", probability: 200000000, color: "text-blue-400", glowColor: "#60a5fa", tierName: "Sky", rarityId: FishRarityId.SKY },
    { id: 53, name: "Thunder Trout", description: "Loudest fish in the sea.", probability: 250000000, color: "text-yellow-400 animate-pulse", glowColor: "#facc15", tierName: "Sky", rarityId: FishRarityId.SKY },
    { id: 54, name: "Wind Whale", description: "Floats on a breeze.", probability: 300000000, color: "text-cyan-100", glowColor: "#cffafe", tierName: "Sky", rarityId: FishRarityId.SKY },
    { id: 55, name: "Solar Salmon", description: "Swims up light beams.", probability: 350000000, color: "text-orange-400", glowColor: "#fb923c", tierName: "Sky", rarityId: FishRarityId.SKY },
    { id: 56, name: "Starfish (Literal)", description: "Five points, burning hot.", probability: 400000000, color: "text-yellow-200", glowColor: "#fef08a", tierName: "Sky", rarityId: FishRarityId.SKY },
    { id: 57, name: "Moon Jelly", description: "Controls the tides.", probability: 450000000, color: "text-indigo-200", glowColor: "#c7d2fe", tierName: "Sky", rarityId: FishRarityId.SKY },
    { id: 58, name: "Aurora Angler", description: "Lights up the north.", probability: 500000000, color: "text-green-400", glowColor: "#4ade80", tierName: "Sky", rarityId: FishRarityId.SKY },
    { id: 59, name: "Vacuum Viper", description: "Breathes nothing.", probability: 600000000, color: "text-neutral-800", glowColor: "#262626", tierName: "Sky", rarityId: FishRarityId.SKY },
    { id: 60, name: "Comet Cod", description: "Returns every 76 years.", probability: 700000000, color: "text-cyan-300", glowColor: "#67e8f9", tierName: "Sky", rarityId: FishRarityId.SKY },
    // --- TIER 7: MAGMA (61-70) ---
    { id: 61, name: "Lava Lamprey", description: "Sucks heat.", probability: 800000000, color: "text-red-600", glowColor: "#dc2626", tierName: "Magma", rarityId: FishRarityId.MAGMA },
    { id: 62, name: "Obsidian Orca", description: "Sharp skin.", probability: 900000000, color: "text-purple-950", glowColor: "#3b0764", tierName: "Magma", rarityId: FishRarityId.MAGMA },
    { id: 63, name: "Magma Minnow", description: "Tiny spark.", probability: 1000000000, color: "text-orange-500", glowColor: "#f97316", tierName: "Magma", rarityId: FishRarityId.MAGMA },
    { id: 64, name: "Ash Anchovy", description: "Tastes burnt.", probability: 1200000000, color: "text-stone-500", glowColor: "#78716c", tierName: "Magma", rarityId: FishRarityId.MAGMA },
    { id: 65, name: "Fire Flounder", description: "Flat and hot.", probability: 1400000000, color: "text-red-500", glowColor: "#ef4444", tierName: "Magma", rarityId: FishRarityId.MAGMA },
    { id: 66, name: "Brimstone Bass", description: "Smells like sulfur.", probability: 1600000000, color: "text-yellow-600", glowColor: "#ca8a04", tierName: "Magma", rarityId: FishRarityId.MAGMA },
    { id: 67, name: "Thermal Tetra", description: "Seeks heat sources.", probability: 1800000000, color: "text-rose-400", glowColor: "#fb7185", tierName: "Magma", rarityId: FishRarityId.MAGMA },
    { id: 68, name: "Pyro Piranha", description: "Boils the water.", probability: 2000000000, color: "text-orange-600 animate-pulse", glowColor: "#ea580c", tierName: "Magma", rarityId: FishRarityId.MAGMA },
    { id: 69, name: "Cinder Crab", description: "Walks on coals.", probability: 2500000000, color: "text-stone-800", glowColor: "#292524", tierName: "Magma", rarityId: FishRarityId.MAGMA },
    { id: 70, name: "Molten Marlin", description: "Liquid metal body.", probability: 3000000000, color: "text-red-400", glowColor: "#f87171", tierName: "Magma", rarityId: FishRarityId.MAGMA },
    // --- TIER 8: DREAM (71-80) ---
    { id: 71, name: "Nightmare Eel", description: "You can't wake up.", probability: 3500000000, color: "text-black bg-white px-1", glowColor: "#000000", tierName: "Dream", rarityId: FishRarityId.DREAM },
    { id: 72, name: "Lucid Lobster", description: "It knows it's a lobster.", probability: 4000000000, color: "text-blue-300", glowColor: "#93c5fd", tierName: "Dream", rarityId: FishRarityId.DREAM }
];
