import { Plant, PlantRarityId } from '../../types';

export const PLANTS: Plant[] = [
    // --- TIER 1: COMMON FLORA (1-10) ---
    { id: 1, name: "Dandelion", description: "Make a wish.", probability: 2, color: "text-yellow-300", glowColor: "#fde047", tierName: "Common", rarityId: PlantRarityId.COMMON },
    { id: 2, name: "Crabgrass", description: "Persistent and annoying.", probability: 3, color: "text-green-700", glowColor: "#15803d", tierName: "Common", rarityId: PlantRarityId.COMMON },
    { id: 3, name: "Clover", description: "Three leaves, standard luck.", probability: 4, color: "text-green-500", glowColor: "#22c55e", tierName: "Common", rarityId: PlantRarityId.COMMON },
    { id: 4, name: "Daisy", description: "She loves me, she loves me not.", probability: 5, color: "text-white", glowColor: "#ffffff", tierName: "Common", rarityId: PlantRarityId.COMMON },
    { id: 5, name: "Thistle", description: "Prickly to the touch.", probability: 6, color: "text-purple-400", glowColor: "#a855f7", tierName: "Common", rarityId: PlantRarityId.COMMON },
    { id: 6, name: "Nettle", description: "Stings if you aren't careful.", probability: 8, color: "text-green-400", glowColor: "#4ade80", tierName: "Common", rarityId: PlantRarityId.COMMON },
    { id: 7, name: "Fern", description: "Ancient plant life.", probability: 10, color: "text-emerald-600", glowColor: "#059669", tierName: "Common", rarityId: PlantRarityId.COMMON },
    { id: 8, name: "Ivy", description: "Climbing up the walls.", probability: 12, color: "text-teal-700", glowColor: "#0f766e", tierName: "Common", rarityId: PlantRarityId.COMMON },
    { id: 9, name: "Moss", description: "Soft and fuzzy.", probability: 15, color: "text-lime-600", glowColor: "#65a30d", tierName: "Uncommon", rarityId: PlantRarityId.UNCOMMON },
    { id: 10, name: "Bamboo", description: "Grows incredibly fast.", probability: 20, color: "text-green-300", glowColor: "#86efac", tierName: "Uncommon", rarityId: PlantRarityId.UNCOMMON },

    // --- TIER 2: EXOTIC (11-20) ---
    { id: 11, name: "Orchid", description: "Delicate and beautiful.", probability: 25, color: "text-fuchsia-300", glowColor: "#f0abfc", tierName: "Uncommon", rarityId: PlantRarityId.UNCOMMON },
    { id: 12, name: "Lotus", description: "Blooms from the mud.", probability: 30, color: "text-pink-200", glowColor: "#fbcfe8", tierName: "Uncommon", rarityId: PlantRarityId.UNCOMMON },
    { id: 13, name: "Venus Flytrap", description: "Bites back.", probability: 40, color: "text-red-500", glowColor: "#ef4444", tierName: "Uncommon", rarityId: PlantRarityId.UNCOMMON },
    { id: 14, name: "Corpse Flower", description: "Smells terrible.", probability: 50, color: "text-red-900", glowColor: "#7f1d1d", tierName: "Uncommon", rarityId: PlantRarityId.UNCOMMON },
    { id: 15, name: "Pitcher Plant", description: "Traps unsuspecting insects.", probability: 60, color: "text-lime-500", glowColor: "#84cc16", tierName: "Rare", rarityId: PlantRarityId.RARE },
    { id: 16, name: "Cactus", description: "Survives in the desert.", probability: 75, color: "text-green-800", glowColor: "#166534", tierName: "Rare", rarityId: PlantRarityId.RARE },
    { id: 17, name: "Bonsai", description: "Tiny tree, big patience.", probability: 100, color: "text-stone-500", glowColor: "#78716c", tierName: "Rare", rarityId: PlantRarityId.RARE },
    { id: 18, name: "Red Rose", description: "Symbol of romance.", probability: 125, color: "text-red-600", glowColor: "#dc2626", tierName: "Rare", rarityId: PlantRarityId.RARE },
    { id: 19, name: "Sunflower", description: "Always faces the light.", probability: 150, color: "text-yellow-400", glowColor: "#facc15", tierName: "Rare", rarityId: PlantRarityId.RARE },
    { id: 20, name: "Lavender", description: "Calming scent.", probability: 200, color: "text-violet-400", glowColor: "#a78bfa", tierName: "Rare", rarityId: PlantRarityId.RARE },

    // --- TIER 3: MAGICAL (21-30) ---
    { id: 21, name: "Mandrake", description: "Screams when uprooted.", probability: 300, color: "text-amber-600", glowColor: "#d97706", tierName: "Magical", rarityId: PlantRarityId.MAGICAL },
    { id: 22, name: "Wolfsbane", description: "Keeps lycanthropes away.", probability: 400, color: "text-indigo-600", glowColor: "#4f46e5", tierName: "Magical", rarityId: PlantRarityId.MAGICAL },
    { id: 23, name: "Nightshade", description: "Deadly poison.", probability: 500, color: "text-purple-900", glowColor: "#581c87", tierName: "Magical", rarityId: PlantRarityId.MAGICAL },
    { id: 24, name: "Glowberry", description: "Natural light source.", probability: 600, color: "text-yellow-200 animate-pulse", glowColor: "#fef08a", tierName: "Magical", rarityId: PlantRarityId.MAGICAL },
    { id: 25, name: "Mana Herb", description: "Restores magical energy.", probability: 750, color: "text-blue-400", glowColor: "#60a5fa", tierName: "Magical", rarityId: PlantRarityId.MAGICAL },
    { id: 26, name: "Golden Apple Tree", description: "Fruit of immortality.", probability: 1000, color: "text-yellow-500", glowColor: "#eab308", tierName: "Epic", rarityId: PlantRarityId.EPIC },
    { id: 27, name: "Phoenix Flower", description: "Bursts into flames.", probability: 1250, color: "text-orange-500", glowColor: "#f97316", tierName: "Epic", rarityId: PlantRarityId.EPIC },
    { id: 28, name: "Crystal Fern", description: "Made of pure glass.", probability: 1500, color: "text-cyan-200", glowColor: "#a5f3fc", tierName: "Epic", rarityId: PlantRarityId.EPIC },
    { id: 29, name: "Whispering Willow", description: "Tells secrets in the wind.", probability: 2000, color: "text-slate-400", glowColor: "#94a3b8", tierName: "Epic", rarityId: PlantRarityId.EPIC },
    { id: 30, name: "Ghost Pepper", description: "Spicier than death.", probability: 2500, color: "text-white drop-shadow-md", glowColor: "#ffffff", tierName: "Epic", rarityId: PlantRarityId.EPIC },

    // --- TIER 4: CELESTIAL (31-40) ---
    { id: 31, name: "Moon Bloom", description: "Opens only at night.", probability: 3500, color: "text-indigo-200", glowColor: "#c7d2fe", tierName: "Celestial", rarityId: PlantRarityId.CELESTIAL },
    { id: 32, name: "Sun Petal", description: "Hot to the touch.", probability: 4500, color: "text-orange-400", glowColor: "#fb923c", tierName: "Celestial", rarityId: PlantRarityId.CELESTIAL },
    { id: 33, name: "Stardust Lily", description: "Sprinkles cosmic dust.", probability: 6000, color: "text-yellow-100", glowColor: "#fef9c3", tierName: "Celestial", rarityId: PlantRarityId.CELESTIAL },
    { id: 34, name: "Nebula Vine", description: "Swirls with colors.", probability: 8000, color: "text-fuchsia-500", glowColor: "#d946ef", tierName: "Celestial", rarityId: PlantRarityId.CELESTIAL },
    { id: 35, name: "Comet Creeper", description: "Trails ice behind it.", probability: 10000, color: "text-cyan-400", glowColor: "#22d3ee", tierName: "Celestial", rarityId: PlantRarityId.CELESTIAL },
    { id: 36, name: "Void Shroom", description: "Consumes surrounding matter.", probability: 12500, color: "text-violet-950", glowColor: "#4c1d95", tierName: "Void", rarityId: PlantRarityId.VOID },
    { id: 37, name: "Galaxy Rose", description: "Petals contain stars.", probability: 15000, color: "text-transparent bg-clip-text bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500", glowColor: "#a855f7", tierName: "Cosmic", rarityId: PlantRarityId.COSMIC },
    { id: 38, name: "Asteroid Moss", description: "Grows in a vacuum.", probability: 20000, color: "text-stone-400", glowColor: "#a8a29e", tierName: "Cosmic", rarityId: PlantRarityId.COSMIC },
    { id: 39, name: "Plasma Root", description: "Crackles with energy.", probability: 25000, color: "text-red-400 animate-pulse", glowColor: "#f87171", tierName: "Cosmic", rarityId: PlantRarityId.COSMIC },
    { id: 40, name: "Black Hole Berry", description: "Infinite density flavor.", probability: 30000, color: "text-black bg-white px-1", glowColor: "#000000", tierName: "Singularity", rarityId: PlantRarityId.SINGULARITY },

    // --- TIER 5: ABSTRACT (41-50) ---
    { id: 41, name: "Yggdrasil Leaf", description: "From the World Tree.", probability: 50000, color: "text-emerald-400", glowColor: "#34d399", tierName: "Mythic", rarityId: PlantRarityId.MYTHIC },
    { id: 42, name: "Life Fruit", description: "Increases max health.", probability: 75000, color: "text-rose-400 animate-pulse", glowColor: "#fb7185", tierName: "Mythic", rarityId: PlantRarityId.MYTHIC },
    { id: 43, name: "Time Flower", description: "Petals fall upwards.", probability: 100000, color: "text-teal-400", glowColor: "#2dd4bf", tierName: "Chrono", rarityId: PlantRarityId.CHRONO },
    { id: 44, name: "Reality Root", description: "Anchors existence.", probability: 150000, color: "text-neutral-200", glowColor: "#e5e5e5", tierName: "Reality", rarityId: PlantRarityId.REALITY },
    { id: 45, name: "Glitch Grass", description: "Texture missing.", probability: 250000, color: "text-fuchsia-600 bg-black", glowColor: "#c026d3", tierName: "Glitch", rarityId: PlantRarityId.GLITCH },
    { id: 46, name: "Binary Bark", description: "01001111.", probability: 500000, color: "text-green-500 font-mono", glowColor: "#22c55e", tierName: "Digital", rarityId: PlantRarityId.DIGITAL },
    { id: 47, name: "Quantum Tulip", description: "Both bloomed and withered.", probability: 1000000, color: "text-blue-300 blur-[1px]", glowColor: "#93c5fd", tierName: "Quantum", rarityId: PlantRarityId.QUANTUM },
    { id: 48, name: "The First Seed", description: "Origin of all flora.", probability: 2500000, color: "text-white drop-shadow-[0_0_15px_white]", glowColor: "#ffffff", tierName: "Primordial", rarityId: PlantRarityId.PRIMORDIAL },
    { id: 49, name: "Eden's Apple", description: "Forbidden knowledge.", probability: 5000000, color: "text-red-500 animate-bounce", glowColor: "#ef4444", tierName: "Divine", rarityId: PlantRarityId.DIVINE },
    { id: 50, name: "Omniflower", description: "Every scent at once.", probability: 10000000, color: "text-transparent bg-clip-text bg-gradient-to-r from-red-500 via-green-500 to-blue-500 animate-pulse", glowColor: "#ffffff", tierName: "Alpha", rarityId: PlantRarityId.ALPHA },
    // --- TIER 6: CODE (51-60) ---
    { id: 51, name: "Comment Weed", description: "// Ignored by the compiler.", probability: 15000000, color: "text-gray-500", glowColor: "#6b7280", tierName: "Code", rarityId: PlantRarityId.CODE },
    { id: 52, name: "Syntax Sprout", description: "Must be perfectly placed.", probability: 20000000, color: "text-green-600", glowColor: "#16a34a", tierName: "Code", rarityId: PlantRarityId.CODE },
    { id: 53, name: "Variable Vine", description: "Changes constantly.", probability: 25000000, color: "text-blue-400", glowColor: "#60a5fa", tierName: "Code", rarityId: PlantRarityId.CODE },
    { id: 54, name: "Boolean Bush", description: "True or False.", probability: 30000000, color: "text-yellow-500", glowColor: "#eab308", tierName: "Code", rarityId: PlantRarityId.CODE },
    { id: 55, name: "Null Nettle", description: "Points to nothing.", probability: 35000000, color: "text-red-400", glowColor: "#f87171", tierName: "Code", rarityId: PlantRarityId.CODE },
    { id: 56, name: "String Grass", description: "Made of characters.", probability: 40000000, color: "text-orange-300", glowColor: "#fdba74", tierName: "Code", rarityId: PlantRarityId.CODE },
    { id: 57, name: "Array Anemone", description: "Indexed from zero.", probability: 45000000, color: "text-cyan-400", glowColor: "#22d3ee", tierName: "Code", rarityId: PlantRarityId.CODE },
    { id: 58, name: "Loop Lily", description: "Blooms forever.", probability: 50000000, color: "text-purple-400", glowColor: "#a855f7", tierName: "Code", rarityId: PlantRarityId.CODE },
    { id: 59, name: "Function Fern", description: "Returns oxygen.", probability: 60000000, color: "text-emerald-500", glowColor: "#10b981", tierName: "Code", rarityId: PlantRarityId.CODE },
    { id: 60, name: "Class Clover", description: "Object oriented.", probability: 70000000, color: "text-indigo-400", glowColor: "#818cf8", tierName: "Code", rarityId: PlantRarityId.CODE },
    // --- TIER 7: NETWORK (61-70) ---
    { id: 61, name: "Packet Petunia", description: "Sent in pieces.", probability: 80000000, color: "text-blue-500", glowColor: "#3b82f6", tierName: "Network", rarityId: PlantRarityId.NETWORK },
    { id: 62, name: "Router Rose", description: "Directs traffic.", probability: 90000000, color: "text-green-500", glowColor: "#22c55e", tierName: "Network", rarityId: PlantRarityId.NETWORK },
    { id: 63, name: "Firewall Ficus", description: "Blocks intruders.", probability: 100000000, color: "text-red-600", glowColor: "#dc2626", tierName: "Network", rarityId: PlantRarityId.NETWORK },
    { id: 64, name: "Bandwidth Bamboo", description: "Grows as fast as your connection.", probability: 120000000, color: "text-yellow-400", glowColor: "#facc15", tierName: "Network", rarityId: PlantRarityId.NETWORK },
    { id: 65, name: "WiFi Willow", description: "Strong signal.", probability: 140000000, color: "text-cyan-500", glowColor: "#06b6d4", tierName: "Network", rarityId: PlantRarityId.NETWORK },
    { id: 66, name: "VPN Violet", description: "Hidden location.", probability: 160000000, color: "text-purple-500", glowColor: "#a855f7", tierName: "Network", rarityId: PlantRarityId.NETWORK },
    { id: 67, name: "DNS Daisy", description: "Resolves names.", probability: 180000000, color: "text-orange-400", glowColor: "#fb923c", tierName: "Network", rarityId: PlantRarityId.NETWORK },
    { id: 68, name: "SSL Sunflower", description: "Secure connection.", probability: 200000000, color: "text-green-400", glowColor: "#4ade80", tierName: "Network", rarityId: PlantRarityId.NETWORK },
    { id: 69, name: "Proxy Poppy", description: "Stands in for another.", probability: 250000000, color: "text-pink-400", glowColor: "#f472b6", tierName: "Network", rarityId: PlantRarityId.NETWORK },
    { id: 70, name: "Cache Cactus", description: "Stores water and data.", probability: 300000000, color: "text-emerald-600", glowColor: "#059669", tierName: "Network", rarityId: PlantRarityId.NETWORK },
    // --- TIER 8: MALWARE (71-80) ---
    { id: 71, name: "Virus Verbena", description: "Infects the garden.", probability: 350000000, color: "text-red-500 animate-pulse", glowColor: "#ef4444", tierName: "Malware", rarityId: PlantRarityId.MALWARE },
    { id: 72, name: "Worm Wisteria", description: "Spreads everywhere.", probability: 400000000, color: "text-purple-600", glowColor: "#9333ea", tierName: "Malware", rarityId: PlantRarityId.MALWARE },
    { id: 73, name: "Trojan Tulip", description: "Looks like a gift.", probability: 450000000, color: "text-yellow-600", glowColor: "#ca8a04", tierName: "Malware", rarityId: PlantRarityId.MALWARE },
    { id: 74, name: "Ransomware Rafflesia", description: "Locks your garden.", probability: 500000000, color: "text-red-800", glowColor: "#991b1b", tierName: "Malware", rarityId: PlantRarityId.MALWARE },
    { id: 75, name: "Spyware Sage", description: "Watching you.", probability: 600000000, color: "text-blue-600", glowColor: "#2563eb", tierName: "Malware", rarityId: PlantRarityId.MALWARE },
    { id: 76, name: "Rootkit Reed", description: "Buried deep.", probability: 700000000, color: "text-stone-700", glowColor: "#44403c", tierName: "Malware", rarityId: PlantRarityId.MALWARE },
    { id: 77, name: "Keylogger Kudzu", description: "Records every step.", probability: 800000000, color: "text-green-700", glowColor: "#15803d", tierName: "Malware", rarityId: PlantRarityId.MALWARE },
    { id: 78, name: "Botnet Begonia", description: "Part of a swarm.", probability: 900000000, color: "text-cyan-600", glowColor: "#0891b2", tierName: "Malware", rarityId: PlantRarityId.MALWARE },
    { id: 79, name: "Phishing Philodendron", description: "Baits you in.", probability: 1000000000, color: "text-orange-500", glowColor: "#f97316", tierName: "Malware", rarityId: PlantRarityId.MALWARE },
    { id: 80, name: "Zero-Day Zinnia", description: "No cure.", probability: 1200000000, color: "text-red-500 font-bold", glowColor: "#ef4444", tierName: "Malware", rarityId: PlantRarityId.MALWARE },
    // --- TIER 9: QUANTUM (81-90) ---
    { id: 81, name: "Qubit Orchid", description: "0 and 1 at once.", probability: 1500000000, color: "text-violet-400 blur-[1px]", glowColor: "#a78bfa", tierName: "Quantum", rarityId: PlantRarityId.QUANTUM },
    { id: 82, name: "Entangled Elm", description: "Connected to another.", probability: 1800000000, color: "text-blue-400", glowColor: "#60a5fa", tierName: "Quantum", rarityId: PlantRarityId.QUANTUM },
    { id: 83, name: "Schrödinger's Seed", description: "Sprouted and not.", probability: 2100000000, color: "text-gray-400", glowColor: "#9ca3af", tierName: "Quantum", rarityId: PlantRarityId.QUANTUM },
    { id: 84, name: "Heisenberg Herb", description: "Uncertain location.", probability: 2500000000, color: "text-teal-400", glowColor: "#2dd4bf", tierName: "Quantum", rarityId: PlantRarityId.QUANTUM },
    { id: 85, name: "Decoherence Dahlia", description: "Collapses when seen.", probability: 3000000000, color: "text-pink-400", glowColor: "#f472b6", tierName: "Quantum", rarityId: PlantRarityId.QUANTUM },
    { id: 86, name: "Quantum Foam Fern", description: "Bubbling reality.", probability: 3500000000, color: "text-white animate-pulse", glowColor: "#ffffff", tierName: "Quantum", rarityId: PlantRarityId.QUANTUM },
    { id: 87, name: "Planck Rose", description: "Smallest possible flower.", probability: 4000000000, color: "text-red-300", glowColor: "#fca5a5", tierName: "Quantum", rarityId: PlantRarityId.QUANTUM }
];
